/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.41
 * Generated at: 2025-05-26 16:44:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>DineEase - Restaurant Table Reservation</title>\n");
      out.write("  <style>\n");
      out.write("    :root {\n");
      out.write("      --primary: #ff6b6b;\n");
      out.write("      --primary-dark: #ff5252;\n");
      out.write("      --secondary: #4ecdc4;\n");
      out.write("      --dark: #292f36;\n");
      out.write("      --light: #f7fff7;\n");
      out.write("      --accent: #ffe66d;\n");
      out.write("      --gray: #6c757d;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    * {\n");
      out.write("      margin: 0;\n");
      out.write("      padding: 0;\n");
      out.write("      box-sizing: border-box;\n");
      out.write("      font-family: 'Poppins', sans-serif;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    body {\n");
      out.write("      background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);\n");
      out.write("      color: var(--dark);\n");
      out.write("      min-height: 100vh;\n");
      out.write("      overflow-x: hidden;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .container {\n");
      out.write("      max-width: 1200px;\n");
      out.write("      margin: 0 auto;\n");
      out.write("      padding: 2rem;\n");
      out.write("      position: relative;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    header {\n");
      out.write("      display: flex;\n");
      out.write("      justify-content: space-between;\n");
      out.write("      align-items: center;\n");
      out.write("      padding: 1rem 0;\n");
      out.write("      margin-bottom: 2rem;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .logo {\n");
      out.write("      font-size: 2rem;\n");
      out.write("      font-weight: 700;\n");
      out.write("      color: var(--primary);\n");
      out.write("      display: flex;\n");
      out.write("      align-items: center;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .logo i {\n");
      out.write("      margin-right: 0.5rem;\n");
      out.write("      color: var(--primary);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .admin-login {\n");
      out.write("      padding: 0.5rem 1rem;\n");
      out.write("      background-color: var(--dark);\n");
      out.write("      color: white;\n");
      out.write("      border-radius: 50px;\n");
      out.write("      font-size: 0.9rem;\n");
      out.write("      text-decoration: none;\n");
      out.write("      transition: all 0.3s ease;\n");
      out.write("      display: flex;\n");
      out.write("      align-items: center;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .admin-login i {\n");
      out.write("      margin-right: 0.5rem;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .admin-login:hover {\n");
      out.write("      background-color: var(--primary);\n");
      out.write("      transform: translateY(-2px);\n");
      out.write("      box-shadow: 0 4px 8px rgba(0,0,0,0.1);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .hero {\n");
      out.write("      text-align: center;\n");
      out.write("      padding: 3rem 0;\n");
      out.write("      margin-bottom: 3rem;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .hero h1 {\n");
      out.write("      font-size: 3.5rem;\n");
      out.write("      margin-bottom: 1rem;\n");
      out.write("      background: linear-gradient(to right, var(--primary), var(--secondary));\n");
      out.write("      -webkit-background-clip: text;\n");
      out.write("      -webkit-text-fill-color: transparent;\n");
      out.write("      animation: fadeInUp 1s ease;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .hero p {\n");
      out.write("      font-size: 1.2rem;\n");
      out.write("      color: var(--gray);\n");
      out.write("      max-width: 700px;\n");
      out.write("      margin: 0 auto 2rem;\n");
      out.write("      animation: fadeInUp 1s ease 0.2s forwards;\n");
      out.write("      opacity: 0;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .features {\n");
      out.write("      display: grid;\n");
      out.write("      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\n");
      out.write("      gap: 2rem;\n");
      out.write("      margin-bottom: 3rem;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .feature-card {\n");
      out.write("      background: white;\n");
      out.write("      border-radius: 10px;\n");
      out.write("      padding: 2rem;\n");
      out.write("      box-shadow: 0 5px 15px rgba(0,0,0,0.05);\n");
      out.write("      transition: all 0.3s ease;\n");
      out.write("      text-align: center;\n");
      out.write("      opacity: 0;\n");
      out.write("      animation: fadeInUp 0.5s ease forwards;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .feature-card:nth-child(1) { animation-delay: 0.4s; }\n");
      out.write("    .feature-card:nth-child(2) { animation-delay: 0.6s; }\n");
      out.write("    .feature-card:nth-child(3) { animation-delay: 0.8s; }\n");
      out.write("\n");
      out.write("    .feature-card:hover {\n");
      out.write("      transform: translateY(-10px);\n");
      out.write("      box-shadow: 0 15px 30px rgba(0,0,0,0.1);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .feature-icon {\n");
      out.write("      font-size: 2.5rem;\n");
      out.write("      margin-bottom: 1rem;\n");
      out.write("      color: var(--primary);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .feature-card h3 {\n");
      out.write("      margin-bottom: 1rem;\n");
      out.write("      color: var(--dark);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .feature-card p {\n");
      out.write("      color: var(--gray);\n");
      out.write("      font-size: 0.9rem;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .action-buttons {\n");
      out.write("      display: flex;\n");
      out.write("      flex-wrap: wrap;\n");
      out.write("      justify-content: center;\n");
      out.write("      gap: 1rem;\n");
      out.write("      margin-bottom: 3rem;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .btn {\n");
      out.write("      padding: 0.8rem 1.5rem;\n");
      out.write("      border-radius: 50px;\n");
      out.write("      font-size: 1rem;\n");
      out.write("      font-weight: 500;\n");
      out.write("      text-decoration: none;\n");
      out.write("      transition: all 0.3s ease;\n");
      out.write("      display: inline-flex;\n");
      out.write("      align-items: center;\n");
      out.write("      justify-content: center;\n");
      out.write("      min-width: 180px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .btn-primary {\n");
      out.write("      background-color: var(--primary);\n");
      out.write("      color: white;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .btn-primary:hover {\n");
      out.write("      background-color: var(--primary-dark);\n");
      out.write("      transform: translateY(-3px);\n");
      out.write("      box-shadow: 0 5px 15px rgba(255, 107, 107, 0.3);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .btn-secondary {\n");
      out.write("      background-color: var(--secondary);\n");
      out.write("      color: white;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .btn-secondary:hover {\n");
      out.write("      background-color: #3dbeb6;\n");
      out.write("      transform: translateY(-3px);\n");
      out.write("      box-shadow: 0 5px 15px rgba(78, 205, 196, 0.3);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .btn-outline {\n");
      out.write("      border: 2px solid var(--primary);\n");
      out.write("      color: var(--primary);\n");
      out.write("      background: transparent;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .btn-outline:hover {\n");
      out.write("      background-color: var(--primary);\n");
      out.write("      color: white;\n");
      out.write("      transform: translateY(-3px);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .btn i {\n");
      out.write("      margin-right: 0.5rem;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    footer {\n");
      out.write("      text-align: center;\n");
      out.write("      padding: 2rem 0;\n");
      out.write("      color: var(--gray);\n");
      out.write("      font-size: 0.9rem;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    @keyframes fadeInUp {\n");
      out.write("      from {\n");
      out.write("        opacity: 0;\n");
      out.write("        transform: translateY(20px);\n");
      out.write("      }\n");
      out.write("      to {\n");
      out.write("        opacity: 1;\n");
      out.write("        transform: translateY(0);\n");
      out.write("      }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    @media (max-width: 768px) {\n");
      out.write("      .hero h1 {\n");
      out.write("        font-size: 2.5rem;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .hero p {\n");
      out.write("        font-size: 1rem;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .features {\n");
      out.write("        grid-template-columns: 1fr;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .action-buttons {\n");
      out.write("        flex-direction: column;\n");
      out.write("        align-items: center;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .btn {\n");
      out.write("        width: 100%;\n");
      out.write("        max-width: 250px;\n");
      out.write("      }\n");
      out.write("    }\n");
      out.write("  </style>\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"container\">\n");
      out.write("  <header>\n");
      out.write("    <div class=\"logo\">\n");
      out.write("      <i class=\"fas fa-utensils\"></i>\n");
      out.write("      <span>DineEase</span>\n");
      out.write("    </div>\n");
      out.write("    <a href=\"adminLogin.jsp\" class=\"admin-login\">\n");
      out.write("      <i class=\"fas fa-lock\"></i>\n");
      out.write("      Admin Login\n");
      out.write("    </a>\n");
      out.write("  </header>\n");
      out.write("\n");
      out.write("  <section class=\"hero\">\n");
      out.write("    <h1>Experience Seamless Dining</h1>\n");
      out.write("    <p>Book your table, explore our menu, and enjoy a hassle-free dining experience with DineEase</p>\n");
      out.write("  </section>\n");
      out.write("\n");
      out.write("  <section class=\"features\">\n");
      out.write("    <div class=\"feature-card\">\n");
      out.write("      <div class=\"feature-icon\">\n");
      out.write("        <i class=\"fas fa-calendar-alt\"></i>\n");
      out.write("      </div>\n");
      out.write("      <h3>Easy Reservations</h3>\n");
      out.write("      <p>Book your table in just a few clicks with our intuitive reservation system</p>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"feature-card\">\n");
      out.write("      <div class=\"feature-icon\">\n");
      out.write("        <i class=\"fas fa-utensils\"></i>\n");
      out.write("      </div>\n");
      out.write("      <h3>Digital Menu</h3>\n");
      out.write("      <p>Browse our delicious offerings and place orders directly from your table</p>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"feature-card\">\n");
      out.write("      <div class=\"feature-icon\">\n");
      out.write("        <i class=\"fas fa-star\"></i>\n");
      out.write("      </div>\n");
      out.write("      <h3>Share Feedback</h3>\n");
      out.write("      <p>Help us improve by sharing your dining experience with us</p>\n");
      out.write("    </div>\n");
      out.write("  </section>\n");
      out.write("\n");
      out.write("  <div class=\"action-buttons\">\n");
      out.write("      <!-- Existing buttons -->\n");
      out.write("      <a href=\"userTables\" class=\"btn btn-primary\">\n");
      out.write("          <i class=\"fas fa-bookmark\"></i> Reserve a Table\n");
      out.write("      </a>\n");
      out.write("      <a href=\"categoryMenu\" class=\"btn btn-secondary\">\n");
      out.write("          <i class=\"fas fa-book-open\"></i> View Menu\n");
      out.write("      </a>\n");
      out.write("\n");
      out.write("      <!-- NEW QUEUE BUTTONS -->\n");
      out.write("      <a href=\"reservationQueue\" class=\"btn btn-warning\">\n");
      out.write("          <i class=\"fas fa-clock\"></i> Queue Management\n");
      out.write("      </a>\n");
      out.write("      <a href=\"login.jsp\" class=\"btn btn-outline\">\n");
      out.write("          <i class=\"fas fa-sign-in-alt\"></i> Customer Login\n");
      out.write("      </a>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <div class=\"action-buttons\">\n");
      out.write("    <a href=\"userAddOrder.jsp\" class=\"btn btn-primary\">\n");
      out.write("      <i class=\"fas fa-shopping-bag\"></i> Place Order\n");
      out.write("    </a>\n");
      out.write("    <a href=\"submitReview.jsp\" class=\"btn btn-secondary\">\n");
      out.write("      <i class=\"fas fa-comment-alt\"></i> Add Feedback\n");
      out.write("    </a>\n");
      out.write("    <a href=\"userReviews\" class=\"btn btn-outline\">\n");
      out.write("      <i class=\"fas fa-star\"></i> View Reviews\n");
      out.write("    </a>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <footer>\n");
      out.write("    <p>&copy; 2025 DineEase Restaurant. All rights reserved.</p>\n");
      out.write("  </footer>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("  // Smooth scrolling for anchor links\n");
      out.write("  document.querySelectorAll('a[href^=\"#\"]').forEach(anchor => {\n");
      out.write("    anchor.addEventListener('click', function(e) {\n");
      out.write("      e.preventDefault();\n");
      out.write("      document.querySelector(this.getAttribute('href')).scrollIntoView({\n");
      out.write("        behavior: 'smooth'\n");
      out.write("      });\n");
      out.write("    });\n");
      out.write("  });\n");
      out.write("\n");
      out.write("  // Animation on scroll\n");
      out.write("  const animateOnScroll = () => {\n");
      out.write("    const elements = document.querySelectorAll('.feature-card');\n");
      out.write("\n");
      out.write("    elements.forEach(element => {\n");
      out.write("      const elementPosition = element.getBoundingClientRect().top;\n");
      out.write("      const screenPosition = window.innerHeight / 1.2;\n");
      out.write("\n");
      out.write("      if(elementPosition < screenPosition) {\n");
      out.write("        element.style.animation = `fadeInUp 0.5s ease forwards`;\n");
      out.write("      }\n");
      out.write("    });\n");
      out.write("  };\n");
      out.write("\n");
      out.write("  window.addEventListener('scroll', animateOnScroll);\n");
      out.write("  document.addEventListener('DOMContentLoaded', animateOnScroll);\n");
      out.write("\n");
      out.write("  // Button hover effects\n");
      out.write("  const buttons = document.querySelectorAll('.btn');\n");
      out.write("  buttons.forEach(button => {\n");
      out.write("    button.addEventListener('mouseenter', () => {\n");
      out.write("      button.style.transform = 'translateY(-3px)';\n");
      out.write("    });\n");
      out.write("    button.addEventListener('mouseleave', () => {\n");
      out.write("      button.style.transform = 'translateY(0)';\n");
      out.write("    });\n");
      out.write("  });\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
